In [1]:
import sqlite3
import pandas as pd

In [2]:
player_performance = pd.read_csv(
    "../Cleaned Data/player_performance.csv"
)

team_summary = pd.read_csv(
    "../Cleaned Data/team_summary.csv"
)

In [3]:
conn = sqlite3.connect(
    "../SQL/triple_threat.db"
)

In [4]:
player_performance.to_sql(
    "player_performance",
    conn,
    if_exists="replace",
    index=False
)

team_summary.to_sql(
    "team_summary",
    conn,
    if_exists="replace",
    index=False
)

3

In [5]:
query = """
SELECT *
FROM player_performance
LIMIT 5;
"""

pd.read_sql_query(query, conn)

,Player Name,Team Name,Batting_Rank,Batting Hand,Batting_Matches,Batting_Innings,Batting_Runs,Balls,Batting_Highest,N/O,...,Batting_Highest_Score,Runs_Per_Ball,Runs_Per_Wicket,Fielding_Dismissals,Runs_Per_Match,Batting_Score,Bowling_Score,Fielding_Score,Overall_Score,Overall_Rank
0,Renoy R,Raging Rhinos,1.0,RHB,5.0,5.0,209.0,77.0,78*,3.0,...,78.0,2.71,61.0,6.0,41.80,100.00,10.00,100.00,68.50,3
1,Jerry Jefferson,Night Hawks,2.0,RHB,5.0,5.0,156.0,63.0,50,2.0,...,50.0,2.48,17.0,2.0,31.20,94.74,80.00,80.95,87.51,1
2,Saravan,Bull Sharks,3.0,RHB,4.0,4.0,109.0,50.0,50,2.0,...,50.0,2.18,31.0,0.0,27.25,89.47,40.00,0.00,58.74,5
3,Jomon Joseph,Night Hawks,4.0,RHB,5.0,3.0,68.0,33.0,48*,1.0,...,48.0,2.06,NaN,4.0,13.60,84.21,NaN,95.24,56.39,6
4,Eby Jio,Raging Rhinos,5.0,-,5.0,5.0,56.0,42.0,24*,4.0,...,24.0,1.33,32.0,0.0,11.20,78.95,33.33,0.00,51.14,9

In [13]:
query = """
SELECT "Player Name", "Team Name", Batting_Runs, Batting
FROM player_performance
WHERE Batting_Runs >= 50
ORDER BY Batting_Runs DESC;
"""

pd.read_sql_query(query, conn)

       Player Name      Team Name  Batting_Runs
0          Renoy R  Raging Rhinos         209.0
1  Jerry Jefferson    Night Hawks         156.0
2          Saravan    Bull Sharks         109.0
3     Jomon Joseph    Night Hawks          68.0
4          Eby Jio  Raging Rhinos          56.0
5   Roofas Clement  Raging Rhinos          52.0
6   Aneesh Cricket  Raging Rhinos          52.0

In [11]:
query = """
SELECT "Player Name", "Team Name", Batting_Runs
FROM player_performance
ORDER BY Batting_Runs DESC
LIMIT 5;
"""

pd.read_sql_query(query, conn)

       Player Name      Team Name  Batting_Runs
0          Renoy R  Raging Rhinos         209.0
1  Jerry Jefferson    Night Hawks         156.0
2          Saravan    Bull Sharks         109.0
3     Jomon Joseph    Night Hawks          68.0
4          Eby Jio  Raging Rhinos          56.0

In [17]:
query = """
SELECT  "Team Name", SUM(Batting_Runs) AS Total_runs
FROM player_performance
GROUP BY "Team Name"
ORDER BY Total_Runs DESC;
"""

pd.read_sql_query(query, conn)

       Team Name  Total_runs
0  Raging Rhinos       380.0
1    Night Hawks       343.0
2    Bull Sharks       218.0

In [21]:
query = """
SELECT  "Team Name", SUM(Wickets) AS Total_wickets, SUM(Bowling_Runs) AS Runs_Conceded,
    ROUND(SUM(Bowling_Runs) * 6.0 / SUM(Overs_Balls), 2) AS Economy
FROM player_performance
GROUP BY "Team Name"
ORDER BY Total_wickets DESC;
"""

pd.read_sql_query(query, conn)

       Team Name  Total_wickets  Runs_Conceded  Economy
0    Night Hawks             13            333    11.68
1  Raging Rhinos             12            395    13.17
2    Bull Sharks              4            319    13.48

In [24]:
query = """
SELECT COUNT(*)
FROM pragma_table_info('player_performance');
"""

pd.read_sql_query(query, conn)

   COUNT(*)
0        48

In [27]:
query = """
SELECT  "Player Name", "Team Name", ROUND((Batting_Runs/Balls)*100,2) AS strike_rate
FROM player_performance
ORDER BY strike_rate DESC
LIMIT 5;
"""

pd.read_sql_query(query, conn)

       Player Name      Team Name  strike_rate
0          Renoy R  Raging Rhinos       271.43
1  Jerry Jefferson    Night Hawks       247.62
2   Aneesh Cricket  Raging Rhinos       247.62
3          Saravan    Bull Sharks       218.00
4     Jomon Joseph    Night Hawks       206.06

In [28]:
query = """
SELECT  "Player Name", "Team Name", ROUND((Batting_Runs/Balls)*100,2) AS strike_rate
FROM player_performance
ORDER BY strike_rate DESC
LIMIT 5;
"""

pd.read_sql_query(query, conn)

       Player Name      Team Name  strike_rate
0          Renoy R  Raging Rhinos       271.43
1  Jerry Jefferson    Night Hawks       247.62
2   Aneesh Cricket  Raging Rhinos       247.62
3          Saravan    Bull Sharks       218.00
4     Jomon Joseph    Night Hawks       206.06

In [30]:
query = """
SELECT  "Player Name", "Team Name", Batting_strike_rate,
CASE WHEN Batting_strike_rate >= 200 THEN "Excellent"
     WHEN Batting_strike_rate >= 150 THEN "Good"
ELSE "Average" END AS Batting_Performance
FROM player_performance
WHERE Batting_runs >= 30
;
"""

pd.read_sql_query(query, conn)

       Player Name      Team Name  Batting_Strike_Rate Batting_Performance
0          Renoy R  Raging Rhinos               271.43           Excellent
1  Jerry Jefferson    Night Hawks               247.62           Excellent
2          Saravan    Bull Sharks               218.00           Excellent
3     Jomon Joseph    Night Hawks               206.06           Excellent
4          Eby Jio  Raging Rhinos               133.33             Average
5   Roofas Clement  Raging Rhinos               200.00           Excellent
6   Aneesh Cricket  Raging Rhinos               247.62           Excellent
7    Aashish Ponnu    Night Hawks               173.08                Good
8    Agraj Mohan S    Bull Sharks               157.69                Good

In [31]:
query = """
SELECT
    "Player Name",
    "Team Name",
    Wickets,
    Bowling_Runs,
    ROUND(Bowling_Runs * 6.0 / Overs_Balls, 2) AS Economy
FROM player_performance
WHERE Wickets > 0
ORDER BY Wickets DESC, Economy ASC
;
"""

pd.read_sql_query(query, conn)

        Player Name      Team Name  Wickets  Bowling_Runs  Economy
0          Amal Psc    Night Hawks        4            48     9.60
1      Gokul Sankar    Night Hawks        4            86    17.20
2    Roofas Clement  Raging Rhinos        3            40    10.00
3   Jerry Jefferson    Night Hawks        2            34     8.50
4     Aashish Ponnu    Night Hawks        2            55    11.00
5           Eby Jio  Raging Rhinos        2            64    12.80
6     Sanal Kumar S  Raging Rhinos        2            53    13.25
7    Aneesh Cricket  Raging Rhinos        2            59    14.75
8           Saravan    Bull Sharks        2            62    15.50
9       Jijo Antony    Bull Sharks        1            28     7.00
10            Abhin  Raging Rhinos        1            57    11.40
11    Jithin Antony    Night Hawks        1            63    12.60
12   Abhishek Mohan    Bull Sharks        1            59    14.75
13          Renoy R  Raging Rhinos        1            61    15.25
14          Manu Ms  Raging Rhinos        1            61    15.25

In [35]:
query = """
SELECT  "Player Name", "Team Name", Batting_runs,
DENSE_RANK() OVER(ORDER BY Batting_runs DESC) AS rnk
FROM player_performance
WHERE Batting_runs IS NOT NULL

;
"""

pd.read_sql_query(query, conn)

        Player Name      Team Name  Batting_Runs  rnk
0           Renoy R  Raging Rhinos         209.0    1
1   Jerry Jefferson    Night Hawks         156.0    2
2           Saravan    Bull Sharks         109.0    3
3      Jomon Joseph    Night Hawks          68.0    4
4           Eby Jio  Raging Rhinos          56.0    5
5    Roofas Clement  Raging Rhinos          52.0    6
6    Aneesh Cricket  Raging Rhinos          52.0    6
7     Aashish Ponnu    Night Hawks          45.0    7
8     Agraj Mohan S    Bull Sharks          41.0    8
9       Jijo Antony    Bull Sharks          29.0    9
10    Jithin Antony    Night Hawks          28.0   10
11      Sam Cricket    Bull Sharks          26.0   11
12         Amal Psc    Night Hawks          19.0   12
13       Litto Tomy    Night Hawks          14.0   13
14     Gokul Sankar    Night Hawks          13.0   14
15   Abhishek Mohan    Bull Sharks          12.0   15
16          Manu Ms  Raging Rhinos           9.0   16
17            Abhin  Raging Rhinos           2.0   17
18     Arjun Sankar    Bull Sharks           1.0   18

In [40]:
query = """
SELECT  "Team Name", SUM(Batting_runs) AS total_runs,
DENSE_RANK() OVER(ORDER BY SUM(Batting_runs) DESC) AS team_rnk
FROM player_performance
Group BY "Team Name"
ORDER BY team_rnk
;
"""

pd.read_sql_query(query, conn)

       Team Name  total_runs  team_rnk
0  Raging Rhinos       380.0         1
1    Night Hawks       343.0         2
2    Bull Sharks       218.0         3

In [42]:
query = """
SELECT
    "Player Name",
    "Team Name",
    Batting_Runs,
    Wickets
FROM player_performance
WHERE Batting_Runs >= 30
  AND Wickets >= 1
ORDER BY Batting_Runs DESC, Wickets DESC;
"""

pd.read_sql_query(query, conn)

       Player Name      Team Name  Batting_Runs  Wickets
0          Renoy R  Raging Rhinos         209.0        1
1  Jerry Jefferson    Night Hawks         156.0        2
2          Saravan    Bull Sharks         109.0        2
3          Eby Jio  Raging Rhinos          56.0        2
4   Roofas Clement  Raging Rhinos          52.0        3
5   Aneesh Cricket  Raging Rhinos          52.0        2
6    Aashish Ponnu    Night Hawks          45.0        2

In [48]:
query = """
with econ AS(
SELECT "Player Name",
    "Team Name",
    Wickets,
    Batting_runs,
    Fielding_Dismissals,
    Bowling_Runs,
    ROUND(Bowling_Runs * 6.0 / Overs_Balls, 2) AS Economy
FROM player_performance
)
SELECT
    "Player Name",
    "Team Name",
    Batting_Runs,
    Wickets,
    Fielding_Dismissals,
    Economy
FROM econ
WHERE Batting_Runs >= 20
  AND Wickets >= 1
  AND Fielding_Dismissals >= 1
  AND Economy < 15
ORDER BY Batting_Runs DESC, Wickets DESC, Fielding_Dismissals DESC, Economy ASC;
"""

pd.read_sql_query(query, conn)

,Player Name,Team Name,Batting_runs,Wickets,Fielding_Dismissals,Economy
0,Jerry Jefferson,Night Hawks,156.0,2,2.0,8.5
1,Roofas Clement,Raging Rhinos,52.0,3,2.0,10.0
2,Jithin Antony,Night Hawks,28.0,1,1.0,12.6

In [49]:
query = """
SELECT
    "Player Name",
    "Team Name",
    Batting_Score,
    Bowling_Score,
    Fielding_Score,
    Overall_Score,
    DENSE_RANK() OVER(ORDER BY Overall_Score DESC) AS Overall_Rank
FROM player_performance
WHERE Overall_Score IS NOT NULL
ORDER BY Overall_Rank;
"""

pd.read_sql_query(query, conn)

,Player Name,Team Name,Batting_Score,Bowling_Score,Fielding_Score,Overall_Score,Overall_Rank
0,Jerry Jefferson,Night Hawks,94.74,80.00,80.95,87.51,1
1,Roofas Clement,Raging Rhinos,71.05,86.67,80.95,78.00,2
2,Renoy R,Raging Rhinos,100.00,10.00,100.00,68.50,3
3,Amal Psc,Night Hawks,36.84,93.33,59.52,60.01,4
4,Saravan,Bull Sharks,89.47,40.00,0.00,58.74,5
5,Jomon Joseph,Night Hawks,84.21,NaN,95.24,56.39,6
6,Aashish Ponnu,Night Hawks,63.16,60.00,0.00,52.58,7
7,Aneesh Cricket,Raging Rhinos,71.05,46.67,0.00,51.86,8
8,Eby Jio,Raging Rhinos,78.95,33.33,0.00,51.14,9
9,Gokul Sankar,Night Hawks,26.32,73.33,80.95,50.97,10
10,Jijo Antony,Bull Sharks,52.63,53.33,0.00,44.98,11
11,Jithin Antony,Night Hawks,47.37,0.00,59.52,32.61,12
12,Sam Cricket,Bull Sharks,42.11,NaN,59.52,29.98,13
13,Agraj Mohan S,Bull Sharks,57.89,NaN,0.00,28.94,14
14,Litto Tomy,Night Hawks,31.58,NaN,80.95,27.93,15
15,Abhishek Mohan,Bull Sharks,21.05,20.00,59.52,26.45,16
16,Manu Ms,Raging Rhinos,15.79,10.00,80.95,23.54,17
17,Sanal Kumar S,Raging Rhinos,NaN,66.67,0.00,23.33,18
18,Abhin,Raging Rhinos,10.53,26.67,0.00,14.60,19
19,Arjun Sankar,Bull Sharks,5.26,NaN,0.00,2.63,20
20,Ebin Cricket,Bull Sharks,NaN,NaN,0.00,0.00,21